image: gitpod/workspace-full

additionalRepositories:
  - url: https://github.com/gitpod-demos/voting-app-result
    checkoutLocation: result
  - url: https://github.com/gitpod-demos/voting-app-vote
    checkoutLocation: https://github.com/gitpod-demos/voting-app-vote
  - url: https://github.com/gitpod-demos/voting-app-worker
    checkoutLocation: worker

tasks:
  - name: Build
    init: |
      # wait for multirepo to finish
      sleep 15
      docker pull postgres:15-alpine
      docker-compose build
    command: |
      printf "Waiting for Voting App at $(gp url 5000) ...\n"
      gp ports await 5000
      cat << EOF
      Voting at $(gp url 5000)
      Results at $(gp url 5001)
      EOF
      code architecture.excalidraw.png
  - name: Run
    init: |
      # wait for multirepo to finish
      sleep 15
    command: docker-compose -f docker-compose.yml up
    openMode: split-right

ports:
  - port: 5000
    onOpen: ignore
  - port: 5001  # results
    onOpen: open-preview
  - port: 5858
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python